#
#   AGREGAR DATOS - TABLA USUARIO_GRUPO
#

INSERT INTO `USUARIO_GRUPO` (`UG_ID`, `UG_NOMBRE`) VALUES
(1, 'ADMINISTRADOR'),
(2, 'PROCESOS'),
(3, 'CAJERO'),
(4, 'CONTADOR'),
(5, 'ADMINISTRACION'),
(6, 'TOMA DE MUESTRA'),
(7, 'VENTAS'),
(8, 'NO SE VE BIEN');

#
#   AGREGAR DATOS - TABLA USUARIO
#

INSERT INTO `USUARIO` (`USU_ID`, `USU_NOMBRE`, `USU_USER`, `USU_PASS`, `USU_ESTADO`, `USU_ACTIVO`, `UG_ID`) VALUES
(1, 'JORGE CRESPO', 'JORGE', 'JORGE', 0, 0, 1),
(2, 'JULIO ACUÑA', 'JULIO', 'JULIO', 0, 0, 1),
(3, 'KEVIN SANDOVAL', 'KEVIN', 'KEVIN', 0, 0, 2),
(4, 'HENRY VALDIVIEZO', 'HENRRY', 'HENRRY', 0, 0, 2),
(5, 'ROSARIO CHAPOÑAN', 'ROSARIO', 'ROSARIO', 1, 1, 3),
(6, 'LIZETH PEÑA', 'LIZETH', 'LIZETH', 0, 0, 3),
(7, 'YESSICA ROCA', 'YESSICA', 'YESSICA', 0, 0, 4),
(8, 'HOMERO GOMEZ', 'HOMERO', 'HOMERO', 0, 0, 4),
(9, 'YSABEL VIZCARRA', 'YSABEL', 'YSABEL', 0, 0, 5),
(10, 'RONALD ROQUE', 'RONALD', 'RONAL', 0, 0, 5)

