#
#   CREAR BASE DE DATOS CRUD_PHP_COLG_ING
#

CREATE DATABASE crud_php_colg_ing CHARSET= utf8 COLLATE=utf8_spanish_ci;

USE crud_php_colg_ing;

#
#   CREAR TABLAS
#

CREATE TABLE USUARIO(
    USU_ID          INT(12) NOT NULL AUTO_INCREMENT,
    USU_NOMBRE      VARCHAR(150) NOT NULL,
    USU_USER        VARCHAR(50) NOT NULL,
    USU_PASS        VARCHAR(260) NOT NULL,
    USU_ESTADO      INT(1) NOT NULL,
    USU_ACTIVO      INT(1) NOT NULL,
    UG_ID           INT(12) NOT NULL,
    PRIMARY KEY (USU_ID)
)ENGINE=InnoDB DEFAULT CHARSET= utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE USUARIO_GRUPO
(
    UG_ID       INT(12) AUTO_INCREMENT,
    UG_NOMBRE   VARCHAR(50),
    PRIMARY KEY (UG_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


ALTER TABLE USUARIO
ADD FOREIGN KEY UG_USU (UG_ID) REFERENCES USUARIO_GRUPO (UG_ID);
